# Generated by Django 5.2.18 on 2026-10-08 10:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acquisitions', '0001_initial'),
        ('locations', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area_unit', models.CharField(choices=[('sqft', 'Sq ft'), ('sqyard', 'Sq yard (Gaj)'), ('sqm', 'Sq metre'), ('biswa', 'Biswa'), ('bigha', 'Bigha'), ('acre', 'Acre'), ('hectare', 'Hectare')], default='sqyard', max_length=10)),
                ('area_sq_meter', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('property_type', models.CharField(choices=[('residential_plot', 'Residential Plot'), ('commercial_plot', 'Commercial Plot'), ('agricultural_land', 'Agricultural Land'), ('farmhouse_land', 'Farmhouse Land'), ('industrial_land', 'Industrial Land'), ('old_construction', 'Plot with Old Construction')], max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('road_width_ft', models.PositiveIntegerField(blank=True, null=True)),
                ('facing', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('sold', 'Sold')], default='available', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acquisition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing', to='acquisitions.acquisition')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.locality')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('site_visit', 'Site visit done'), ('negotiating', 'Negotiating'), ('closed', 'Deal closed'), ('lost', 'Not interested')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_referrals', to='partners.channelpartner')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='listings.listing')),
            ],
            options={
                'verbose_name_plural': 'buyer inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
