# Generated by Django 5.2.18 on 2026-10-08 10:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('firm_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 digit Indian mobile number starting with 6, 7, 8 or 9.', regex='^[6-9]\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rera_agent_number', models.CharField(blank=True, max_length=40, verbose_name='RERA agent number (optional)')),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('areas_covered', models.ManyToManyField(blank=True, related_name='partners', to='locations.locality')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
