# Generated by Django 5.2.18 on 2026-10-08 10:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import submissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=120, verbose_name='Full name')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 digit Indian mobile number starting with 6, 7, 8 or 9.', regex='^[6-9]\\d{9}$')], verbose_name='Mobile number')),
                ('whatsapp', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 digit Indian mobile number starting with 6, 7, 8 or 9.', regex='^[6-9]\\d{9}$')], verbose_name='WhatsApp number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relation', models.CharField(choices=[('owner', 'Owner'), ('co_owner', 'Co-owner'), ('poa', 'Power of Attorney holder'), ('family', 'Family member')], default='owner', max_length=10, verbose_name='Your relation to property')),
                ('phone_verified', models.BooleanField(default=False)),
                ('property_type', models.CharField(choices=[('residential_plot', 'Residential Plot'), ('commercial_plot', 'Commercial Plot'), ('agricultural_land', 'Agricultural Land'), ('farmhouse_land', 'Farmhouse Land'), ('industrial_land', 'Industrial Land'), ('old_construction', 'Plot with Old Construction')], max_length=30)),
                ('village_colony', models.CharField(blank=True, max_length=120, verbose_name='Village / colony name')),
                ('khasra_number', models.CharField(blank=True, max_length=60, verbose_name='Khasra / Gata number')),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True, verbose_name='Full address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('area_unit', models.CharField(choices=[('sqft', 'Sq ft'), ('sqyard', 'Sq yard (Gaj)'), ('sqm', 'Sq metre'), ('biswa', 'Biswa'), ('bigha', 'Bigha'), ('acre', 'Acre'), ('hectare', 'Hectare')], default='sqyard', max_length=10)),
                ('area_sq_meter', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('road_width_ft', models.PositiveIntegerField(blank=True, null=True, verbose_name='Road width (ft)')),
                ('frontage_ft', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frontage (ft)')),
                ('facing', models.CharField(blank=True, choices=[('east', 'East'), ('west', 'West'), ('north', 'North'), ('south', 'South'), ('north_east', 'North-East'), ('north_west', 'North-West'), ('south_east', 'South-East'), ('south_west', 'South-West')], max_length=12)),
                ('is_corner', models.BooleanField(default=False, verbose_name='Corner plot')),
                ('has_boundary_wall', models.BooleanField(default=False, verbose_name='Boundary wall')),
                ('has_electricity', models.BooleanField(default=False, verbose_name='Electricity connection')),
                ('water_source', models.CharField(blank=True, choices=[('municipal', 'Municipal supply'), ('borewell', 'Borewell / Submersible'), ('handpump', 'Hand pump'), ('none', 'None')], max_length=12)),
                ('distance_main_road_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Distance from main road (metres)')),
                ('irrigation_source', models.CharField(blank=True, choices=[('tubewell', 'Tubewell'), ('canal', 'Canal'), ('rain', 'Rain-fed'), ('none', 'None')], max_length=12)),
                ('current_crop', models.CharField(blank=True, max_length=80)),
                ('soil_type', models.CharField(blank=True, choices=[('alluvial', 'Alluvial (Domat)'), ('sandy', 'Sandy (Balui)'), ('clay', 'Clay (Matiyar)'), ('mixed', 'Mixed')], max_length=12)),
                ('has_tubewell', models.BooleanField(default=False, verbose_name='Tubewell / borewell on land')),
                ('ownership_type', models.CharField(choices=[('single', 'Single owner'), ('joint', 'Joint ownership')], default='single', max_length=10)),
                ('number_of_owners', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('title_documents', models.JSONField(blank=True, default=list)),
                ('mutation_done', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not sure')], default='not_sure', max_length=10, verbose_name='Mutation (Dakhil Kharij) done')),
                ('approval_status', models.CharField(choices=[('ada', 'ADA approved'), ('rera', 'RERA registered project'), ('not_approved', 'Not approved / unplanned'), ('na', 'Not applicable (agricultural)'), ('not_sure', 'Not sure')], default='not_sure', max_length=15, verbose_name='ADA / RERA status')),
                ('has_loan', models.BooleanField(default=False, verbose_name='Any loan on property')),
                ('has_dispute', models.BooleanField(default=False, verbose_name='Any court dispute')),
                ('encumbrance_details', models.TextField(blank=True)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_negotiable', models.BooleanField(default=True)),
                ('reason_for_selling', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('1_month', 'Within 1 month'), ('1_3_months', '1 to 3 months'), ('exploring', 'Just exploring')], default='1_3_months', max_length=12)),
                ('preferred_visit_time', models.CharField(blank=True, choices=[('morning', 'Morning (9am - 12pm)'), ('afternoon', 'Afternoon (12pm - 4pm)'), ('evening', 'Evening (4pm - 7pm)'), ('weekend', 'Weekends only')], max_length=12)),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('visit_scheduled', 'Site Visit Scheduled'), ('visit_done', 'Site Visit Done'), ('under_evaluation', 'Under Evaluation'), ('legal_verification', 'Legal Verification'), ('offer_made', 'Offer Made'), ('negotiation', 'Negotiation'), ('offer_accepted', 'Offer Accepted'), ('acquired', 'Acquired'), ('rejected', 'Rejected'), ('withdrew', 'Owner Withdrew')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('partner', 'Channel partner')], default='website', max_length=10)),
                ('is_complete', models.BooleanField(default=False, help_text='Full form filled (not only quick lead)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='locations.locality')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_referrals', to='partners.channelpartner')),
                ('tehsil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.tehsil')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('visit_scheduled', 'Site Visit Scheduled'), ('visit_done', 'Site Visit Done'), ('under_evaluation', 'Under Evaluation'), ('legal_verification', 'Legal Verification'), ('offer_made', 'Offer Made'), ('negotiation', 'Negotiation'), ('offer_accepted', 'Offer Accepted'), ('acquired', 'Acquired'), ('rejected', 'Rejected'), ('withdrew', 'Owner Withdrew')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('visit_scheduled', 'Site Visit Scheduled'), ('visit_done', 'Site Visit Done'), ('under_evaluation', 'Under Evaluation'), ('legal_verification', 'Legal Verification'), ('offer_made', 'Offer Made'), ('negotiation', 'Negotiation'), ('offer_accepted', 'Offer Accepted'), ('acquired', 'Acquired'), ('rejected', 'Rejected'), ('withdrew', 'Owner Withdrew')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='submissions.propertysubmission')),
            ],
            options={
                'verbose_name_plural': 'status history',
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('registry', 'Registry / Sale Deed'), ('khatauni', 'Khatauni'), ('gpa', 'GPA'), ('will', 'Will'), ('id_proof', 'Owner ID proof'), ('map', 'Site map / Naksha'), ('other', 'Other')], default='other', max_length=12)),
                ('file', models.FileField(storage=submissions.models.private_storage, upload_to=submissions.models.submission_doc_path)),
                ('visible_only_to_company', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='submissions.propertysubmission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=submissions.models.submission_photo_path)),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='submissions.propertysubmission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
