# Generated by Django 5.2.18 on 2026-10-08 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('locality_type', models.CharField(choices=[('urban', 'Urban Colony'), ('highway', 'Highway Belt'), ('village', 'Village / Rural')], default='urban', max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('connectivity', models.TextField(blank=True, help_text='One point per line')),
                ('landmarks', models.TextField(blank=True, help_text='Nearby landmarks, one per line')),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='localities/')),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'localities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocalityFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='locations.locality')),
            ],
            options={
                'verbose_name': 'locality FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='locality',
            name='tehsil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='locations.tehsil'),
        ),
        migrations.CreateModel(
            name='CircleRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial')], max_length=20)),
                ('rate_per_sq_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_year', models.PositiveIntegerField(default=2026)),
                ('is_sample', models.BooleanField(default=True, help_text='Demo data, not official')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_rates', to='locations.locality')),
            ],
            options={
                'ordering': ['locality__name', 'property_type'],
                'unique_together': {('locality', 'property_type', 'effective_year')},
            },
        ),
    ]
